### ISSUE TITLE
Live edit fails with pages having a page template

### ISSUE THREAD

**Issue by aro** [enonic/xp-apps#613]
Live edit fails editing some pages. It seems to depend on if they have a template or controller.

For example in the Features app:
- Edit /features/portal-functions/imageurl
- There is an error message: `"The Live edit page could not be initialized. The rendered page is not consistent with the page components structure. Expected component with index 0 was not found in region 'main'."`

This same page was working with Content Studio 6.13.0

**Comment by sgauruseu** [comment]
Open the Features/Sanitize html

<img width="922" alt="san" src="https://user-images.githubusercontent.com/3728712/36530969-8c47bb9c-17cd-11e8-959e-7887d86ab35b.png">

**Comment by alansemenov** [comment]
@vbradnitski  Looks like this one is not entirely fixed...
Try this:
1. Install Superhero app (so that the site is in New status)
2. Open the Superhero site in the wizard
3. Change display name to something else
4. Publish it

The same error pops up right after the site was published. If you refresh the page, the error no longer appears.
